CREATE TABLE `domain_reporting` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `domain` varchar(100) DEFAULT NULL,
  `advertiser` int(11) DEFAULT NULL,
  `campaign_id` int(11) DEFAULT NULL,
  `line_item` int(11) DEFAULT NULL,
  `imps` int(11) DEFAULT NULL,
  `clicks` int(11) DEFAULT NULL,
  `ctr` float(7,2) DEFAULT NULL,
  `convs` int(11) DEFAULT NULL,
  `pv_convs` int(11) DEFAULT NULL,
  `pc_convs` int(11) DEFAULT NULL,
  `rev` float(7,2) DEFAULT NULL,
  `mc` float(7,2) DEFAULT NULL,
  `profit` float(7,2) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique` (`advertiser`,`domain`,`line_item`,`imps`,`clicks`,`ctr`,`convs`,`pv_convs`,`pc_convs`,`rev`,`mc`,`profit`)
)
